import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:geolocator/geolocator.dart';
import '../../../../core/constants/constants.dart';
import '../../../../core/services/location_service.dart';
import '../../../../core/widgets/widgets.dart';
import '../../logic/emergency_cubit.dart';
import '../../logic/emergency_state.dart';
import '../../../auth/logic/auth_cubit.dart';
import '../../data/models/emergency_request_model.dart';

class EmergencyRequestScreen extends StatefulWidget {
  const EmergencyRequestScreen({super.key});

  @override
  State<EmergencyRequestScreen> createState() => _EmergencyRequestScreenState();
}

class _EmergencyRequestScreenState extends State<EmergencyRequestScreen> with TickerProviderStateMixin {
  Position? _currentPosition;
  bool _isRequesting = false;
  EmergencyType _selectedType = EmergencyType.sos;
  
  AnimationController? _animationController;
  AnimationController? _pulseController;
  Animation<double>? _growAnimation;
  Animation<double>? _pulseAnimation;
  bool _isGrowing = false;
  
  final Set<Marker> _markers = {};
  GoogleMapController? _mapController;

  @override
  void initState() {
    super.initState();
    _initLocation();
    _initAnimations();
  }

  void _initAnimations() {
    // SOS Activation Animation (Hold to trigger)
    _animationController = AnimationController(
      vsync: this,
      duration: const Duration(seconds: 2),
    );
    
    _growAnimation = Tween<double>(begin: 1.0, end: 15.0).animate(
      CurvedAnimation(parent: _animationController!, curve: Curves.easeInCubic),
    );

    _animationController!.addStatusListener((status) {
      if (status == AnimationStatus.completed) {
        _sendEmergencyRequest();
      }
    });

    // Idle Pulse Animation
    _pulseController = AnimationController(
      vsync: this,
      duration: const Duration(seconds: 2),
    )..repeat(reverse: true);

    _pulseAnimation = Tween<double>(begin: 1.0, end: 1.1).animate(
      CurvedAnimation(parent: _pulseController!, curve: Curves.easeInOut),
    );
  }

  @override
  void dispose() {
    _animationController?.dispose();
    _pulseController?.dispose();
    super.dispose();
  }

  Future<void> _initLocation() async {
    final pos = await LocationService.getCurrentLocation();
    if (pos != null && mounted) {
      setState(() {
        _currentPosition = pos;
        _markers.add(
          Marker(
            markerId: const MarkerId('user_location'),
            position: LatLng(pos.latitude, pos.longitude),
            infoWindow: const InfoWindow(title: 'My Location'),
          ),
        );
      });
    }
  }

  void _handleTapDown(TapDownDetails details) {
    if (_currentPosition == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text("Unable to get your location. Please try again.")),
      );
      return;
    }
    setState(() => _isGrowing = true);
    _animationController?.forward();
    _pulseController?.stop();
  }

  void _handleTapUp(TapUpDetails details) {
    if (_animationController!.status != AnimationStatus.completed) {
      _animationController?.reverse();
      setState(() => _isGrowing = false);
      _pulseController?.repeat(reverse: true);
    }
  }

  void _handleTapCancel() {
    if (_animationController!.status != AnimationStatus.completed) {
      _animationController?.reverse();
      setState(() => _isGrowing = false);
      _pulseController?.repeat(reverse: true);
    }
  }

  void _sendEmergencyRequest() {
    final authState = context.read<AuthCubit>().state;
    if (authState is! Authenticated) return;

    final request = EmergencyRequest(
      id: '', // Will be generated by DB
      userId: authState.user!.id,
      userName: authState.profile?.fullName ?? "User",
      userPhone: authState.profile?.phoneNumber ?? "",
      type: _selectedType,
      status: EmergencyStatus.pending,
      latitude: _currentPosition!.latitude,
      longitude: _currentPosition!.longitude,
      createdAt: DateTime.now(),
    );

    context.read<EmergencyCubit>().requestEmergency(request);
  }

  void _updateAmbulanceMarker(LatLng position) {
    setState(() {
      _markers.removeWhere((m) => m.markerId.value == 'ambulance_live');
      _markers.add(
        Marker(
          markerId: const MarkerId('ambulance_live'),
          position: position,
          icon: BitmapDescriptor.defaultMarkerWithHue(BitmapDescriptor.hueAzure),
          infoWindow: const InfoWindow(title: 'Ambulance arriving'),
        ),
      );
    });

    if (_currentPosition != null) {
      final bounds = LatLngBounds(
        southwest: LatLng(
          _currentPosition!.latitude < position.latitude ? _currentPosition!.latitude : position.latitude,
          _currentPosition!.longitude < position.longitude ? _currentPosition!.longitude : position.longitude,
        ),
        northeast: LatLng(
          _currentPosition!.latitude > position.latitude ? _currentPosition!.latitude : position.latitude,
          _currentPosition!.longitude > position.longitude ? _currentPosition!.longitude : position.longitude,
        ),
      );
      _mapController?.animateCamera(CameraUpdate.newLatLngBounds(bounds, 50));
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      body: BlocConsumer<EmergencyCubit, EmergencyState>(
        listener: (context, state) {
          if (state is EmergencyActive) {
            setState(() {
              _isRequesting = true;
              _isGrowing = false;
            });
            if (state.ambulance != null) {
              _updateAmbulanceMarker(LatLng(state.ambulance!.latitude, state.ambulance!.longitude));
            }
          } else if (state is EmergencyError) {
            setState(() {
              _isGrowing = false;
              _animationController?.reset();
              _pulseController?.repeat(reverse: true);
            });
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(content: Text(state.message)),
            );
          } else if (state is EmergencySuccess) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text("Emergency assistance has arrived.")),
            );
          }
        },
        builder: (context, state) {
          if (_isRequesting && state is EmergencyActive) {
            return _buildActiveRequestView(state);
          }

          return _buildInitialView();
        },
      ),
    );
  }

  Widget _buildInitialView() {
    if (_growAnimation == null || _animationController == null) {
      return const Center(child: CircularProgressIndicator());
    }

    return Stack(
      children: [
        Column(
          children: [
            AtamanHeader(
              isSimple: true,
              height: 120,
              child: Stack(
                children: [
                  Align(
                    alignment: Alignment.centerLeft,
                    child: IconButton(
                      icon: const Icon(Icons.arrow_back_ios_new, color: Colors.white, size: 20),
                      onPressed: () => Navigator.pop(context),
                    ),
                  ),
                  const Center(
                    child: Text(
                      "Emergency Assistance",
                      style: TextStyle(color: Colors.white, fontSize: 20, fontWeight: FontWeight.bold),
                    ),
                  ),
                ],
              ),
            ),
            Expanded(
              child: Padding(
                padding: const EdgeInsets.all(AppSizes.p24),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    const Text(
                      "Choose emergency type",
                      style: AppTextStyles.h3,
                    ),
                    const SizedBox(height: AppSizes.p24),
                    _buildTypeSelector(),
                    const SizedBox(height: AppSizes.p48),
                    Center(
                      child: Stack(
                        alignment: Alignment.center,
                        children: [
                          // Background progress circle
                          if (_isGrowing)
                            SizedBox(
                              width: 220,
                              height: 220,
                              child: CircularProgressIndicator(
                                value: _animationController!.value,
                                strokeWidth: 8,
                                color: AppColors.danger,
                                backgroundColor: AppColors.danger.withOpacity(0.1),
                              ),
                            ),
                          
                          AnimatedBuilder(
                            animation: Listenable.merge([_growAnimation!, _pulseAnimation!]),
                            builder: (context, child) {
                              return Transform.scale(
                                scale: _isGrowing ? _growAnimation!.value : _pulseAnimation!.value,
                                child: GestureDetector(
                                  onTapDown: _handleTapDown,
                                  onTapUp: _handleTapUp,
                                  onTapCancel: _handleTapCancel,
                                  child: Container(
                                    width: 200,
                                    height: 200,
                                    decoration: BoxDecoration(
                                      color: AppColors.danger,
                                      shape: BoxShape.circle,
                                      boxShadow: [
                                        BoxShadow(
                                          color: AppColors.danger.withOpacity(0.3),
                                          blurRadius: _isGrowing ? 40 : 20,
                                          spreadRadius: _isGrowing ? 20 : 10,
                                        ),
                                      ],
                                    ),
                                    child: Center(
                                      child: Opacity(
                                        opacity: _isGrowing ? (1.0 - (_animationController!.value * 2.0)).clamp(0.0, 1.0) : 1.0,
                                        child: const Column(
                                          mainAxisAlignment: MainAxisAlignment.center,
                                          children: [
                                            Icon(Icons.sos, color: Colors.white, size: 60),
                                            Text(
                                              "HOLD TO SEND",
                                              style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              );
                            },
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(height: AppSizes.p40),
                    Opacity(
                      opacity: _isGrowing ? (1.0 - (_animationController!.value * 5.0)).clamp(0.0, 1.0) : 1.0,
                      child: Column(
                        children: [
                          const Text(
                            "Hold button for 2 seconds to activate",
                            style: AppTextStyles.bodyMedium,
                          ),
                          const SizedBox(height: 8),
                          Text(
                            "Emergency ${_selectedType.name.toUpperCase()} will be sent",
                            style: AppTextStyles.bodySmall.copyWith(color: AppColors.danger),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ],
    );
  }

  Widget _buildTypeSelector() {
    return Opacity(
      opacity: _isGrowing ? (1.0 - (_animationController!.value * 4.0)).clamp(0.0, 1.0) : 1.0,
      child: Wrap(
        spacing: 12,
        runSpacing: 12,
        children: EmergencyType.values.map((type) {
          final isSelected = _selectedType == type;
          return ChoiceChip(
            label: Text(type.name.toUpperCase()),
            selected: isSelected,
            onSelected: (selected) {
              if (selected && !_isGrowing) setState(() => _selectedType = type);
            },
            selectedColor: AppColors.danger,
            labelStyle: TextStyle(color: isSelected ? Colors.white : Colors.black),
          );
        }).toList(),
      ),
    );
  }

  Widget _buildActiveRequestView(EmergencyActive state) {
    final request = state.request;
    final ambulance = state.ambulance;

    return Stack(
      children: [
        GoogleMap(
          initialCameraPosition: CameraPosition(
            target: LatLng(request.latitude, request.longitude),
            zoom: 15,
          ),
          markers: _markers,
          onMapCreated: (controller) => _mapController = controller,
          myLocationEnabled: true,
          myLocationButtonEnabled: true,
        ),
        Positioned(
          top: 0,
          left: 0,
          right: 0,
          child: AtamanHeader(
            isSimple: true,
            height: 100,
            child: Row(
              children: [
                IconButton(
                  icon: const Icon(Icons.arrow_back, color: Colors.white),
                  onPressed: () {
                    context.read<EmergencyCubit>().cancelRequest(request.id);
                    setState(() {
                      _isRequesting = false;
                      _isGrowing = false;
                      _animationController?.reset();
                      _pulseController?.repeat(reverse: true);
                      _markers.removeWhere((m) => m.markerId.value == 'ambulance_live');
                    });
                  },
                ),
                const Text("Tracking Emergency Response", style: TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.bold)),
              ],
            ),
          ),
        ),
        Positioned(
          bottom: 0,
          left: 0,
          right: 0,
          child: Container(
            padding: const EdgeInsets.all(24),
            decoration: const BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
              boxShadow: [BoxShadow(color: Colors.black12, blurRadius: 10)],
            ),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Row(
                  children: [
                    if (ambulance == null)
                      const CircularProgressIndicator(color: AppColors.danger, strokeWidth: 3)
                    else
                      const Icon(Icons.local_shipping, color: AppColors.primary, size: 30),
                    const SizedBox(width: 16),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            ambulance == null
                              ? "Searching for Help"
                              : "Ambulance ${ambulance.plateNumber} En Route",
                            style: AppTextStyles.bodyLarge.copyWith(fontWeight: FontWeight.bold)
                          ),
                          Text(
                            ambulance == null
                              ? "Emergency ${request.type.name.toUpperCase()} Active. Nearest responder is being notified..."
                              : "The ambulance is on its way to your location.",
                            style: AppTextStyles.bodySmall
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 24),
                ElevatedButton(
                  onPressed: () => context.read<EmergencyCubit>().cancelRequest(request.id),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.grey.shade200,
                    foregroundColor: Colors.black,
                    minimumSize: const Size(double.infinity, 50),
                    elevation: 0,
                  ),
                  child: const Text("Cancel Emergency"),
                ),
              ],
            ),
          ),
        ),
      ],
    );
  }
}
