// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBqROpQbqHupulfBg17sII4_Gsxwrf9oM',
    appId: '1:876391655400:web:1dbf9960f0d55ad627a65d',
    messagingSenderId: '876391655400',
    projectId: 'ataman-mayoral-hackathon-2025',
    authDomain: 'ataman-mayoral-hackathon-2025.firebaseapp.com',
    storageBucket: 'ataman-mayoral-hackathon-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsi-g25UD3jhJRTKAudNH0OfSX9lZhxFs',
    appId: '1:876391655400:android:23837207011f2d6b27a65d',
    messagingSenderId: '876391655400',
    projectId: 'ataman-mayoral-hackathon-2025',
    storageBucket: 'ataman-mayoral-hackathon-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaE_qB6uJSfkHEpRF4ZO3XzOA6GGuNcoY',
    appId: '1:876391655400:ios:5637a68b33f5221e27a65d',
    messagingSenderId: '876391655400',
    projectId: 'ataman-mayoral-hackathon-2025',
    storageBucket: 'ataman-mayoral-hackathon-2025.firebasestorage.app',
    iosBundleId: 'com.NBC.ataman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaE_qB6uJSfkHEpRF4ZO3XzOA6GGuNcoY',
    appId: '1:876391655400:ios:5637a68b33f5221e27a65d',
    messagingSenderId: '876391655400',
    projectId: 'ataman-mayoral-hackathon-2025',
    storageBucket: 'ataman-mayoral-hackathon-2025.firebasestorage.app',
    iosBundleId: 'com.NBC.ataman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBqROpQbqHupulfBg17sII4_Gsxwrf9oM',
    appId: '1:876391655400:web:7d860edfae7bd71727a65d',
    messagingSenderId: '876391655400',
    projectId: 'ataman-mayoral-hackathon-2025',
    authDomain: 'ataman-mayoral-hackathon-2025.firebaseapp.com',
    storageBucket: 'ataman-mayoral-hackathon-2025.firebasestorage.app',
  );

}