import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:geolocator/geolocator.dart';
import '../../constants/constants.dart';
import '../../logic/emergency/emergency_cubit.dart';
import '../../logic/emergency/emergency_state.dart';
import '../../logic/auth/auth_cubit.dart';
import '../../data/models/emergency_request_model.dart';
import '../../services/location_service.dart';
import '../../widgets/ataman_simple_header.dart';

class EmergencyRequestScreen extends StatefulWidget {
  const EmergencyRequestScreen({super.key});

  @override
  State<EmergencyRequestScreen> createState() => _EmergencyRequestScreenState();
}

class _EmergencyRequestScreenState extends State<EmergencyRequestScreen> {
  Position? _currentPosition;
  bool _isRequesting = false;
  EmergencyType _selectedType = EmergencyType.sos;

  @override
  void initState() {
    super.initState();
    _initLocation();
  }

  Future<void> _initLocation() async {
    final pos = await LocationService.getCurrentLocation();
    if (pos != null && mounted) {
      setState(() {
        _currentPosition = pos;
      });
    }
  }

  void _sendEmergencyRequest() {
    if (_currentPosition == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text("Unable to get your location. Please try again.")),
      );
      return;
    }

    final authState = context.read<AuthCubit>().state;
    if (authState is! Authenticated) return;

    final request = EmergencyRequest(
      id: '', // Will be generated by DB
      userId: authState.user!.id,
      userName: authState.profile?.fullName ?? "User",
      userPhone: authState.profile?.phoneNumber ?? "",
      type: _selectedType,
      status: EmergencyStatus.pending,
      latitude: _currentPosition!.latitude,
      longitude: _currentPosition!.longitude,
      createdAt: DateTime.now(),
    );

    context.read<EmergencyCubit>().requestEmergency(request);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      body: BlocConsumer<EmergencyCubit, EmergencyState>(
        listener: (context, state) {
          if (state is EmergencyActive) {
            setState(() => _isRequesting = true);
          } else if (state is EmergencyError) {
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(content: Text(state.message)),
            );
          }
        },
        builder: (context, state) {
          if (_isRequesting && state is EmergencyActive) {
            return _buildActiveRequestView(state.request);
          }

          return _buildInitialView();
        },
      ),
    );
  }

  Widget _buildInitialView() {
    return Column(
      children: [
        AtamanSimpleHeader(
          height: 120,
          child: Stack(
            children: [
              Align(
                alignment: Alignment.centerLeft,
                child: IconButton(
                  icon: const Icon(Icons.arrow_back_ios_new, color: Colors.white, size: 20),
                  onPressed: () => Navigator.pop(context),
                ),
              ),
              const Center(
                child: Text(
                  "Emergency Assistance",
                  style: TextStyle(color: Colors.white, fontSize: 20, fontWeight: FontWeight.bold),
                ),
              ),
            ],
          ),
        ),
        Expanded(
          child: Padding(
            padding: const EdgeInsets.all(AppSizes.p24),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                const Text(
                  "Choose emergency type",
                  style: AppTextStyles.h3,
                ),
                const SizedBox(height: AppSizes.p24),
                _buildTypeSelector(),
                const SizedBox(height: AppSizes.p48),
                GestureDetector(
                  onTap: _sendEmergencyRequest,
                  child: Container(
                    width: 200,
                    height: 200,
                    decoration: BoxDecoration(
                      color: AppColors.danger,
                      shape: BoxShape.circle,
                      boxShadow: [
                        BoxShadow(
                          color: AppColors.danger.withOpacity(0.3),
                          blurRadius: 20,
                          spreadRadius: 10,
                        ),
                      ],
                    ),
                    child: const Center(
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Icon(Icons.sos, color: Colors.white, size: 60),
                          Text(
                            "PRESS FOR HELP",
                            style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
                const SizedBox(height: AppSizes.p24),
                const Text(
                  "Hold for 3 seconds to cancel",
                  style: AppTextStyles.bodySmall,
                ),
              ],
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildTypeSelector() {
    return Wrap(
      spacing: 12,
      runSpacing: 12,
      children: EmergencyType.values.map((type) {
        final isSelected = _selectedType == type;
        return ChoiceChip(
          label: Text(type.name.toUpperCase()),
          selected: isSelected,
          onSelected: (selected) {
            if (selected) setState(() => _selectedType = type);
          },
          selectedColor: AppColors.danger,
          labelStyle: TextStyle(color: isSelected ? Colors.white : Colors.black),
        );
      }).toList(),
    );
  }

  //for demo
  Widget _buildActiveRequestView(EmergencyRequest request) {
    return Column(
      children: [
        const AtamanSimpleHeader(height: 100, child: Center(child: Text("Request Active", style: TextStyle(color: Colors.white)))),
        Expanded(
          child: Padding(
            padding: const EdgeInsets.all(24.0),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                const CircularProgressIndicator(color: AppColors.danger),
                const SizedBox(height: 24),
                Text("Emergency ${request.type.name.toUpperCase()} Requested", style: AppTextStyles.h2),
                const SizedBox(height: 8),
                Text("Status: ${request.status.name.toUpperCase()}", style: AppTextStyles.h3.copyWith(color: AppColors.primary)),
                const SizedBox(height: 32),
                const Text("An ambulance and responders are being dispatched to your location.", textAlign: TextAlign.center),
                const SizedBox(height: 48),
                ElevatedButton(
                  onPressed: () => context.read<EmergencyCubit>().cancelRequest(request.id),
                  style: ElevatedButton.styleFrom(backgroundColor: Colors.grey),
                  child: const Text("Cancel Request"),
                ),
              ],
            ),
          ),
        ),
      ],
    );
  }
}
